stages:
- stage: build
  jobs:
  - job: build-dotnet
    pool: Default

    steps:
    - template: ../steps/docker-build.yml
      parameters:
        msbuild: true

        postSteps:
        - task: PublishTestResults@2
          displayName: Publish test results
          inputs:
            testRunner: VSTest
            testResultsFiles: '*.trx'
            searchFolder: $(Agent.TempDirectory)/test
            configuration: Release

        - template: ../steps/publish-code-coverage.yml
