parameters:
  stackName: ''
  certificate: false
  secretEnvironmentFile: false
stages:
- stage: deploy
  condition: and(
    succeeded(),
    eq(variables['Build.SourceBranch'], 'refs/heads/broker'),
    ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: deploy_dev
    pool: Default
    environment: dev

    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadSecureFile@1
            displayName: Download secure file ssh key
            inputs:
              secureFile: id_rsa_xyz_release

          - ${{ if eq(parameters.certificate, 'true') }}:
            - task: DownloadSecureFile@1
              displayName: Download secure file chain (PEM)
              inputs:
                secureFile: fullchain.pem

            - task: DownloadSecureFile@1
              displayName: Download secure file certificate private key
              inputs:
                secureFile: privkey.pem

          - ${{ if eq(parameters.secretEnvironmentFile, 'true') }}:
            - task: DownloadSecureFile@1
              displayName: Download secure file secret environment
              inputs:
                secureFile: secrets.env

          - download: current
            displayName: Download artifact compose file
            artifact: compose

          - bash: |
              set -e
              cd "$(Agent.TempDirectory)"
              cp -v "$(Pipeline.Workspace)/compose/dockerup.yml" .
              chmod 600 id_rsa_xyz_release
              ssh -fNi id_rsa_xyz_release -L localhost:2374:/var/run/docker.sock \
                -o StrictHostKeyChecking=No \
                azureuser@revaturexyz-housing-dev-master.southcentralus.cloudapp.azure.com
              export DOCKER_HOST=localhost:2374
              docker stack rm "${{ parameters.stackName }}" || true
              docker network create -d overlay appnet 2>/dev/null || true
              docker stack deploy -c dockerup.yml "${{ parameters.stackName }}"
            displayName: Deploy Docker stack
